import { StyleSheet } from 'react-native';
import { windowHeight, fontSizes, windowWidth } from '../../theme/appConstant';
import appColors from '../../theme/appColors';
import appFonts from '../../theme/appFonts';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0A0A0C',
  },
  headerContainer: {
    paddingHorizontal: windowWidth(4),
    paddingTop: windowHeight(2),
    paddingBottom: windowHeight(1.5),
    backgroundColor: '#12141A',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.08)',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: fontSizes.FONT4HALF,
    fontFamily: appFonts.bold,
    color: appColors.white,
    letterSpacing: 0.2,
  },
  headerSub: {
    fontSize: fontSizes.FONT2HALF,
    fontFamily: appFonts.regular,
    color: '#8C929D',
    marginTop: 2,
  },
  statusBadge: {
    backgroundColor: 'rgba(0, 229, 153, 0.15)',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(0, 229, 153, 0.4)',
  },
  statusBadgeText: {
    fontSize: fontSizes.FONT2HALF,
    fontFamily: appFonts.bold,
    color: '#00E599',
    textTransform: 'uppercase',
  },
  modeToggleContainer: {
    flexDirection: 'row',
    backgroundColor: '#181C26',
    marginHorizontal: windowWidth(4),
    marginTop: windowHeight(2),
    borderRadius: 10,
    padding: 4,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.06)',
  },
  modeTab: {
    flex: 1,
    paddingVertical: 10,
    alignItems: 'center',
    borderRadius: 8,
  },
  modeTabActive: {
    backgroundColor: appColors.primary,
  },
  modeTabText: {
    fontSize: fontSizes.FONT3,
    fontFamily: appFonts.medium,
    color: '#8C929D',
  },
  modeTabTextActive: {
    color: appColors.white,
    fontFamily: appFonts.bold,
  },
  scrollContent: {
    paddingHorizontal: windowWidth(4),
    paddingBottom: windowHeight(5),
  },
  planningCard: {
    backgroundColor: '#12141A',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255, 85, 0, 0.2)',
    padding: 16,
    marginTop: windowHeight(2),
  },
  cardHeaderTitle: {
    fontSize: fontSizes.FONT3HALF,
    fontFamily: appFonts.bold,
    color: appColors.white,
    marginBottom: 4,
  },
  cardHeaderDesc: {
    fontSize: fontSizes.FONT2HALF,
    fontFamily: appFonts.regular,
    color: '#8C929D',
    marginBottom: 14,
  },
  inputGroup: {
    marginBottom: 12,
  },
  inputLabel: {
    fontSize: fontSizes.FONT2HALF,
    fontFamily: appFonts.medium,
    color: '#D4AF37',
    marginBottom: 4,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  inputBox: {
    backgroundColor: '#181C26',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: appColors.white,
    fontFamily: appFonts.regular,
    fontSize: fontSizes.FONT3,
  },
  rowInputs: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  deviationChipsRow: {
    flexDirection: 'row',
    marginTop: 6,
    marginBottom: 14,
    gap: 8,
  },
  chip: {
    flex: 1,
    paddingVertical: 8,
    borderRadius: 6,
    backgroundColor: '#181C26',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    alignItems: 'center',
  },
  chipSelected: {
    borderColor: appColors.primary,
    backgroundColor: 'rgba(255, 85, 0, 0.12)',
  },
  chipText: {
    fontSize: fontSizes.FONT2HALF,
    fontFamily: appFonts.medium,
    color: '#8C929D',
  },
  chipTextSelected: {
    color: appColors.primary,
    fontFamily: appFonts.bold,
  },
  actionButton: {
    backgroundColor: appColors.primary,
    borderRadius: 8,
    paddingVertical: 12,
    alignItems: 'center',
    marginTop: 6,
  },
  actionButtonText: {
    color: appColors.white,
    fontSize: fontSizes.FONT3HALF,
    fontFamily: appFonts.bold,
    letterSpacing: 0.3,
  },
  sectionHeading: {
    fontSize: fontSizes.FONT3HALF,
    fontFamily: appFonts.bold,
    color: appColors.white,
    marginTop: windowHeight(2.5),
    marginBottom: windowHeight(1.2),
  },
  freightCard: {
    backgroundColor: '#12141A',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    padding: 16,
    marginBottom: 12,
  },
  freightTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  categoryBadge: {
    backgroundColor: 'rgba(255, 85, 0, 0.12)',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: 'rgba(255, 85, 0, 0.3)',
  },
  categoryBadgeText: {
    color: appColors.primary,
    fontSize: fontSizes.FONT2,
    fontFamily: appFonts.bold,
  },
  deviationTag: {
    fontSize: fontSizes.FONT2HALF,
    color: '#D4AF37',
    fontFamily: appFonts.medium,
  },
  freightTitle: {
    fontSize: fontSizes.FONT3HALF,
    fontFamily: appFonts.bold,
    color: appColors.white,
    marginBottom: 8,
  },
  routeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
  },
  routeDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: appColors.primary,
    marginRight: 8,
  },
  routeDotDrop: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#00E599',
    marginRight: 8,
  },
  routeText: {
    fontSize: fontSizes.FONT2HALF,
    color: '#E0E6ED',
    fontFamily: appFonts.regular,
    flex: 1,
  },
  specsRow: {
    flexDirection: 'row',
    backgroundColor: '#181C26',
    borderRadius: 6,
    padding: 8,
    marginVertical: 10,
    justifyContent: 'space-around',
  },
  specItem: {
    alignItems: 'center',
  },
  specLabel: {
    fontSize: fontSizes.FONT2,
    color: '#8C929D',
    fontFamily: appFonts.regular,
  },
  specVal: {
    fontSize: fontSizes.FONT2HALF,
    color: appColors.white,
    fontFamily: appFonts.bold,
    marginTop: 2,
  },
  priceBreakdownBox: {
    backgroundColor: 'rgba(0, 229, 153, 0.08)',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(0, 229, 153, 0.25)',
    padding: 10,
    marginVertical: 8,
  },
  priceRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 2,
  },
  priceLabel: {
    fontSize: fontSizes.FONT2HALF,
    color: '#8C929D',
    fontFamily: appFonts.regular,
  },
  priceValue: {
    fontSize: fontSizes.FONT2HALF,
    color: '#E0E6ED',
    fontFamily: appFonts.medium,
  },
  netEarningsLabel: {
    fontSize: fontSizes.FONT3,
    color: '#00E599',
    fontFamily: appFonts.bold,
  },
  netEarningsValue: {
    fontSize: fontSizes.FONT4,
    color: '#00E599',
    fontFamily: appFonts.bold,
  },
  bidButton: {
    backgroundColor: '#00E599',
    borderRadius: 8,
    paddingVertical: 10,
    alignItems: 'center',
    marginTop: 6,
  },
  bidButtonText: {
    color: '#0A0A0C',
    fontSize: fontSizes.FONT3,
    fontFamily: appFonts.bold,
  },
});
